# This line needs to come before anything else in Cargo.toml
# cargo-features = ["codegen-backend"]

# [profile.dev]
# codegen-backend = "cranelift"

[package]
name = "cel-rs"
version = "0.1.0"
edition = "2024"
description = "A stack-based runtime for developing domain specific languages"

[dependencies]
anyhow = { workspace = true }
typenum = { workspace = true }
cel-rs-macros = { workspace = true }
itertools = { workspace = true }

[workspace.dependencies]
anyhow = "1.0"
typenum = "1.18.0"
cel-rs-macros = { path = "./cel-rs-macros" }
itertools = "0.14"

[workspace]
members = [".", "cel-rs-macros", "cel-parser"]
